# This is a docker-compose.yml file, not a Dockerfile.
# Rename this file to docker-compose.yml and use 'docker compose up' to run your services.

services:
    sonarqube:
        image: sonarqube:community
        container_name: sonarqube
        ports:
            - "9000:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
            - SONAR_JDBC_USERNAME=sonar
            - SONAR_JDBC_PASSWORD=sonar
        depends_on:
            - db
        restart: unless-stopped

    db:
        image: postgres:15
        container_name: sonarqube-db
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
            - POSTGRES_DB=sonar
        volumes:
            - sonarqube_db_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    sonarqube_db_data: